name: GitHub Snake Animation

on:
  schedule:
    - cron: "0 0 * * *"  # Setiap hari jam 00:00 UTC
  workflow_dispatch:  # Manual run
  push:
    branches: [main]

permissions:
  contents: write  # Izinkan push ke branch output
  actions: write   # Izinkan workflow menulis

jobs:
  generate:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Generate Snake Animations
        uses: Platane/snk@v3
        with:
          github_user_name: ${{ github.repository_owner }}  # Dinamis, ambil dari repo owner
          outputs: |
            dist/snake.svg
            dist/snake-dark.svg?palette=github-dark
            dist/snake.gif
        env:
          GITHUB_TOKEN: ${{ secrets.DEPLOY_TOKEN }}  # Default token

      - name: Deploy to Output Branch
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.DEPLOY_TOKEN }}
          publish_dir: ./dist
          target_branch: output
          commit_message: "Update snake animation [skip ci]"
